name: chat_bubbles
description: Chat bubble widgets, similar to Whatsapp and more shapes. Easy to use and implement
  chat bubbles.
version: 0.7.9+3
homepage: https://github.com/prahack/chat_bubbles
author: Prabhanu Gunaweera <prabhanu96@gmail.com>

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

