name: chat_bubbles
description: This is a simple Flutter widget plugin which can use to implement chat bubbles.
version: 0.7.1+3
homepage: https://github.com/prahack/chat_bubbles

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

